[package]
name = "minecraft-console"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
crossterm = "0.29.0"
regex = "1.12.2"
tokio = {version = "1.48.0", features = ["full"]}
tui = "0.19.0"
